# Copyright 2021 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  generate-self-signed-certificates:
    type: boolean
    default: false
    description: Generate self-signed certificates and ignores provided certificates.
  ca-common-name:
    type: string
    default:
    description: Common name to be used only if `generate-self-signed-certificates` set to true.
  certificate-validity:
    type: int
    default: 365
    description: Certificate validity (in days) only if `generate-self-signed-certificates` set to true.
  certificate:
    type: string
    default:
    description: |
      Base64 encoded TLS certificate (do not use if 'generate-self-signed-certificates' is set to true).
  ca-certificate:
    type: string
    default:
    description: |
      Base64 encoded CA Certificate (do not use if 'generate-self-signed-certificates' is set to true).
  ca-chain:
    type: string
    default:
    description: |
      Base64 encoded CA Chain (do not use if 'generate-self-signed-certificates' is set to true).
