name: Issues to JIRA

on:
  issues:
    types: [opened, reopened, closed]

permissions:
  issues: read

jobs:
  update:
    name: Update Issue
    uses: >-
      canonical/identity-credentials-workflows/.github/workflows/jira-sync.yaml@v0
    secrets:
      JIRA_WEBHOOK_URL: ${{ secrets.JIRA_WEBHOOK_URL }}
      JIRA_WEBHOOK_TOKEN: ${{ secrets.JIRA_WEBHOOK_TOKEN }}
